base/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.get_routes),
    path('rooms/', views.get_rooms),
    path('rooms/<str:pk>', views.get_room),
    path('rooms/<str:pk>/delete', views.delete_room),
    path('rooms/create', views.create_room),
    path('messages/<str:pk>', views.get_messages),
    path('messages/<str:pk>/delete', views.delete_message),
    path('messages/send/<str:pk>', views.send_message),
]

# {
 
 


# }

base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views


urlpatterns = [
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_page, name="register"),
    path("", views.home, name="home"),
    path("room/<str:pk>/", views.room, name="room"),
    path("profile/<str:pk>/", views.user_profile, name="user_profile"),
    path("create_room/", views.create_room, name="create_room"),
    path("update_room/<str:pk>/", views.update_room, name="update_room"),
    path("delete_room/<str:pk>/", views.delete_room, name="delete_room"),
    path("delete_message/<str:pk>/", views.delete_message, name="delete_message"),
    path("update_user/", views.update_user, name="update_user"),
    path("topics/", views.topics_page, name="topics"),
    path("activity/", views.activity_page, name="activity"),
    path("chatroom/", views.chat, name="chatroom"),
    path('addNotes/', views.addNotes, name='addNotes'),
    path('viewNotes/', views.viewNotes, name='viewNotes'),
    path('editNotes/<int:pid>/', views.editNotes, name='editNotes'),
    path('deleteNotes/<int:pid>/', views.deleteNotes, name='deleteNotes'),
    path('courses/', views.courses, name='courses')
]

# Set the URL as MEDIA_URL and then GET the file uploaded from MEDIA_ROOT
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studybuddy/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('base.urls')),
    path('api/', include('base.api.urls')),
]

base/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser,User

#superuser aj, aj@aj.com - aj@123

# Create your models here.

# class User(AbstractUser):
#     name = models.CharField(max_length=200, null=True)
#     email = models.EmailField(unique=True, null=True)
#     bio = models.TextField(null=True)

#     avatar = models.ImageField(null=True, default='avatar.svg')

#     # USERNAME_FIELD = 'email'

#     REQUIRED_FIELDS = []

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE, related_name ='profile')
    bio = models.TextField(null=True)
    avatar = models.ImageField(null=True, default='avatar.svg')
    name = models.CharField(max_length=255,null=True,blank=True)

class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self) -> str:
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]

#################################################################################
class Signup(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ContactNo = models.CharField(max_length=10, null=True)
    About = models.CharField(max_length=450, null=True)
    Role = models.CharField(max_length=150, null=True)
    RegDate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.first_name

class Notes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True,blank=True)
    Title = models.CharField(max_length=200, null=True)
    Content = models.CharField(max_length=450, null=True)
    CreationDate = models.DateTimeField(auto_now_add=True)
    UpdationDate = models.DateField(null=True)

    def __str__(self):
        return self.Title
    
class courses(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True,blank=True)
    name = models.CharField(max_length=200)

#################################################################################   

base/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import Room,Profile
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'avatar', 'bio']

base/api/views.py
from base.models import *
from .serializers import *
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from rest_framework.response import Response # for rest framework api views
from rest_framework.decorators import api_view,permission_classes,parser_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework import status


# Show's us all the routes in our API
@api_view(['GET'])
def get_routes(request):
    routes = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/rooms:id'
    ]
    return Response(routes)

@api_view(['GET'])
@login_required(login_url='login')
def get_rooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)

@api_view(['GET','PUT','PATCH'])
@login_required(login_url='login')
def get_room(request, pk):
  try:
    room = Room.objects.get(id=pk)
    if request.method == 'GET':
        serializer = RoomSerializer(room, many=False)
        return Response(serializer.data)
    if request.method in ['PUT','PATCH']:
        serializer = RoomSerializer(room, data = request.data, partial = request.method == 'PATCH')
        if serializer.is_valid():
           serializer.save()
           return Response(serializer.data)
        
  except Exception as e:
      return Response({'error': str(e)}, status=status.HTTP_400_BAD_REQUEST)

     
     

@api_view(['POST'])
@login_required(login_url='login')
def create_room(request):
   serializer = RoomSerializer(request.data)
   try:
     if(serializer.is_valid()):
        serializer.save()
        return Response(serializer.data)
   except Exception as e:
      return Response({'error': str(e)}, status=status.HTTP_400_BAD_REQUEST)


@api_view(['DELETE']) 
def delete_room(request,pk):
   try:
      room = Room.objects.get(id=pk)
      room.delete()
   except Exception as e:
      return Response({'error': str(e)}, status=status.HTTP_400_BAD_REQUEST)
      
        


@api_view(['POST'])
@login_required(login_url = 'login')
def send_message(request,pk):
  try:
    room = room.objects.get(id = pk)
    serializer = MessageSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response({'message':'Message sent Successfully'},status=status.HTTP_201_CREATED)
  except Exception as e:
         return Response({'error': str(e)}, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET'])
@login_required(login_url = 'login')
def get_messages(request, pk):
  try:
    room = room.objects.get(id = pk)
    messages = Message.objects.get(room = room)
    serializer = MessageSerializer(messages,many=True)
    return Response(serializer.data)
    
  except Exception as e:
         return Response({'error': str(e)}, status=status.HTTP_400_BAD_REQUEST)

@api_view(['DELETE'])
@login_required(login_url='login')
def delete_message(request, pk):
  try:
      message = message.objects.get(id=pk)
      message.delete()
      return Response({'message': 'profile deleted successfully'}, status=status.HTTP_204_NO_CONTENT)
  except Exception as e:
      return Response({'error': str(e)}, status=status.HTTP_400_BAD_REQUEST)

@api_view(['POST'])
@login_required(login_url='login')
def create_topic(request):
   serializer = TopicSerializer(request.data)
   try:
    if serializer.is_valid():
        serializer.save()
        return Response({'message':'Topic Created Successfully'},status=status.HTTP_201_CREATED)
   except Exception as e:
      return Response({'error': str(e)}, status=status.HTTP_400_BAD_REQUEST)
   
@api_view(['GET'])
def get_topics(request):
    topics = Topic.objects.all()
    serializer = TopicSerializer(topics, many=True)
    return Response(serializer.data)




       
   

base/templates/base/activity_component.html
<!--Recent activities container-->

<div class="activities">
    <div class="activities__header">
      <h2>Recent Activities</h2>
    </div>


    <!--Display the user, the message, when the message was created-->
    {% for message in room_messages %}
    <div class="activities__box">
      <div class="activities__boxHeader roomListRoom__header">

        <!--User Profile container-->
        <a href="{% url 'user_profile' message.user.id %}" class="roomListRoom__author">
          <div class="avatar avatar--small">
            <img src="{{ message.user.avatar.url }}" />
          </div>
          <p>
            @{{ message.user }}
            <!--Message Creation Time-->
            <span>{{ message.created|timesince }}</span>
          </p>
        </a>


        <!--Delete/Remove Button for Messages-->
        <!--Only the logged in user can see the Delete Link and delete a message-->

        <div class="roomListRoom__actions">
          {% if request.user == message.user %}
          <a href="{% url 'delete_message' message.id %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>remove</title>
              <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
              ></path>
            </svg>
          </a>
          {% endif %}
        </div>
      </div>

      <!--Replied to 'Message'-->
      {% comment %} <div class="replied"> {% endcomment %}
      <div class="activities__boxContent">
        <p>replied to post “<a href="{% url 'room' message.room.id %}">{{ message.room }}</a>”</p>
        <div class="activities__boxRoomContent">
          {{ message.body }}
                </div>
              </div>
            </div>
            {% endfor %}
  <!--Activity Box Ends-->

base/templates/base/addNotes.html
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>AddNotes</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  -- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
  <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'> 
  
</head>

<!--Body container-->
  <body>
    

    <!--Navbar container-->
    {% include 'navbar.html' %}
    <!-- {% include 'slidebar.html' %} -->
    
    <style>
        .fixed-div {
            position: fixed;
            top: 75px;
            right: 10px;
            width: 80%;
            height: 75%;
            background-color:  --color-dark;
            padding: 10px;
        }
    </style>
    
    <div class="fixed-div">
        <section class="section profile">
            <div class="row">
        
                <div class="col-xl-12">
        
                    <div class="card">
                        <div class="card-body pt-3">
                            <!-- Bordered Tabs -->
                            <ul class="nav nav-tabs nav-tabs-bordered">
        
                                <li class="nav-item">
                                    <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">
                                        Add Notes
                                    </button>
                                </li>
        
                            </ul>
                            <div class="tab-content pt-2">
        
                                <div class="tab-pane fade show active profile-overview" id="profile-overview">
                                    <form method="post">
                                        {% csrf_token %}
        
                                        <div class="row mb-3">
                                           
                                           <div class="col-md-8 col-lg-11">
    <input name="Title" type="text" class="form-control" placeholder="Enter Title" style="font-size: 20px;" required>
</div>

                                        </div>
        
                                        <div class="row mb-3">
                                            
                                            <div class="col-md-8 col-lg-11">
                                                <textarea name="Content" class="form-control" style="height: 300px" placeholder="Notes Description" required></textarea>
                                            </div>
                                        </div>
        
                                        <div class="text-center">
    <button type="submit" class="btn btn-primary" style="color: black;">Submit</button>
</div>

                                    </form><!-- End Profile Edit Form -->
        
                                </div>
        
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        
        {% if error == "no" %}
        <script>
               alert('New Notes Added Successfully.');
               window.location=("{% url 'addNotes' %}");
        </script>   
        {% endif %}
        
        {% if error == "yes" %}
        <script>
                alert('Something went wrong, Try Again');
        </script>
        {% endif %}
    </div>

base/templates/base/delete_form.html
{% extends 'main.html' %}


{% block content %}
<form method="POST" action="">
    {% csrf_token %}
    <p>Are you sure you want to delete this {{ obj }}?</p>
    
    <a href="{{ request.META.HTTP_REFERER }}">Go Back</a>
    <input type="submit" value="Confirm">
    
</form>
    
{% endblock content %}
    

base/templates/base/delete_message_old.html
{% extends 'main.html' %}


{% block content %}
<form method="POST" action="">
    {% csrf_token %}
    <p>Are you sure you want to delete this {{ obj }}?</p>
    
    <a href="{{ request.META.HTTP_REFERER }}">Go Back</a>
    <input type="submit" value="Confirm">
    
</form>
    
{% endblock content %}
    

base/templates/base/feed_component.html
{% for room in rooms %}
<div class="roomListRoom">
    <div class="roomListRoom__header">
        <a href="{% url 'user_profile' room.host.id %}" class="roomListRoom__author">
            <div class="avatar avatar--small">
                <img src="{{room.host.avatar.url}}" />
            </div>
            <span>@{{room.host.username}}</span>
        </a>
        <div class="roomListRoom__actions">
            <span>{{room.created|timesince}} ago</span>
        </div>
    </div>
    <div class="roomListRoom__content">
        <a href="{% url 'room' room.id %}">{{room.name}}</a>
    </div>
    <div class="roomListRoom__meta">
        <a href="{% url 'room' room.id %}" class="roomListRoom__joined">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>user-group</title>
                <path
                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
                </path>
                <path
                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
                </path>
                <path
                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
                </path>
                <path
                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
                </path>
            </svg>
            {{room.participants.all.count}} Joined
        </a>
        <p class="roomListRoom__topic">{{room.topic.name}}</p>
    </div>
</div>
{% endfor %}

base/templates/base/home_old.html.html
{% extends 'main.html' %}


{% block content %}

<!--Styling home-container-->
<style>
    .home-container{
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;
    }
</style>

<!--Home container-->
<div class="home-container">

    <!--Topics container-->
    <div>
        {% include 'base/topics_component.html' %}
    </div>

    <!-- Room container-->
    <div>
        <h5>{{ room_count }} rooms available</h5>
    <a href="{% url 'create_room' %}">Create Room</a>

    {% include 'base/room_component.html' %}
    </div>
            
    
    <!--Recent activities container-->
    <div>
    {% include 'base/activity_component.html' %}
    </div>

</div>
{% endblock content %}

base/templates/base/login_register_old.html
{% extends 'main.html' %}


{% block content %}


{% if page == 'login' %}
<!--Login Form-->
<div>
    <form method="POST" action=""> 
        {% csrf_token %}

        <label>Username:</label>
        <input type="text" name="username" placeholder="Enter Username">
        
        <label>Password:</label>
        <input type="password" name="password" placeholder="Enter Password">
        
        <input type="submit" value="Login">
</form>
<!--If user is not registered go to Register page -->
<p>Haven't signed up yet?</p>
<a href="{% url 'register' %}">Sign Up</a>
</div>

{% else %}

<!--Register Form-->
<div>
    <form method="POST" action=""> 
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
</form>
<!--If user is registered go to Login page -->
<p>Already signed up?</p>
<a href="{% url 'login' %}">Login</a>
</div>
{% endif %} 
{% endblock content %}

base/templates/base/profile.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
  <!--Profile container-->
  <main class=_profile-page layout layout--3">
    <div class="container">
      
        <!-- Browse Topics section on the left -->
        <div class="col-md-3">
          {% include 'base/topics_component.html' %}
        </div>

        <!-- Profile section in the middle -->
        <div class="col-md-6">
          <!-- User details and About section -->
          <div class=_profile">
            <!-- User details -->
            <div class="profile__avatar">
              <div class="avatar avatar--large active">
                <img src="{{ prof.avatar.url }}" alt="{{ user.username }} Avatar" />
              </div>
            </div>
            <div class="profile__info">
              <div>
                <h3>{{ user.username }}</h3>
                <p><a href="{% url 'user_profile' user.id %}">@ {{ user.username }}</a></p>
                <!-- Only the logged-in User can Edit the Profile -->
                {% if request.user == user %}
                  <!-- Edit Profile Button -->
                  <a href="{% url 'update_user' %}" class="btn btn--main btn--pill">Edit Profile</a>
                {% endif %}
              </div>
            </div>

            <!-- About section -->
            <div class="profile__about">
              <h2>About</h2>
              <p>{{ user.bio }}</p>
              <!-- Display the bio update message if available -->
              {% if user.date_joined %}
                <p>Updated {{ user.date_joined|date:"F j, Y" }}</p>
              {% endif %}
            </div>
          </div>

          <!-- Study rooms hosted by the user -->
          <div class="roomList">
            <!-- Room List Start -->
            {% for room in rooms %}
              <div class="roomListRoom">
                <!-- Room Author/Host/User -->
                <a href="{% url 'user_profile' room.host.id %}" class="roomListRoom__author">
                  <div class="avatar avatar--small">
                    <img src="{{ room.host.avatar.url }}" alt="{{ room.host.username }} Avatar" />
                  </div>
                  <span>@{{ room.host.username }}</span>
                </a>

                <!-- Room Creation Time -->
                <div class="roomListRoom__actions">
                  <span>{{ room.created|timesince }}</span>
                </div>

                <!-- Room Content: Name/Description -->
                <div class="roomListRoom__content">
                  <a href="{% url 'room' room.id %}">{{ room.name }}</a>
                </div>

                <!-- Room Participants -->
                <div class="roomListRoom__meta">
                  <a href="{% url 'room' room.id %}" class="roomListRoom__joined">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>user-group</title>
                      <!-- ... (SVG content) ... -->
                    </svg>
                    {{ room.participants.all.count }}
                  </a>
                  <!-- Room's Topic -->
                  <p class="roomListRoom__topic">{{ room.topic.name }}</p>
                </div>
              </div>
            {% endfor %}
            <!-- Room List End -->
          </div>
        </div>

        <!-- Recent Activities section on the right -->
        <div class="col-md-3">
          <div class="activities">
            {% include 'base/activity_component.html' %}
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

base/templates/base/profile_old.html
{% extends 'main.html' %}


{% block content %}
<!--Styling Profile container-->
<style>
    .profile-container{
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;
    }
</style>

<h1> {{ user.username }}</h1>
<!-- Profile container-->
<div class="profile-container">

    <!--Topics Container-->
    <div>
        {% include 'base/topics_component.html' %}
        </div>

    <!--Room Container-->
    <div>
        {% include 'base/room_component.html' %}
    </div>

    <!--Recent Activity Container-->
    <div>
        {% include 'base/activity_component.html' %}
        </div>
    
</div>
    
{% endblock content %}
    

base/templates/base/topics.html
{% extends 'main.html' %}

{% block content %}
    <main class="create-room layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url 'home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Browse Topics</h3>
            </div>
          </div>

          <!--Search bar for Topics-->
          <div class="topics-page layout__body">
            <form action="" method="GET" class="header__search">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name="q" placeholder="Search for topics" />
              </label>
            </form>
         

          <!-- Topics List -->
          <div class="col-md-3">
            <ul class="topics__list">
              <!-- Move this "All" item inside the topics list -->
              <li>
                <a href="{% url 'topics' %}" class="active">All <span>{{ topics.count }}</span></a>
              </li>
              <!-- Iterate through other topics -->
              {% for topic in topics %}
              <li>
                <a href="{% url 'home' %}?q={{ topic.name }}">
                  <span class="topic-name">{{ topic.name }}</span>
                  <span class="topic-count">{{ topic.room_set.all.count }}</span>
                </a>
              </li>
              {% endfor %}
            </ul>
          </div>

        </div>
      </div>
    </main>
    {% endblock content %}

base/templates/base/topics_component.html
<!--Topics container-->

<div class="topics">
    <div class="topics__header">
      <h2>Browse Topics</h2>
    </div>
    <ul class="topics__list">
      <li>
        <a href="{% url 'home' %}" class="active">All <span>{{ topics.count }}</span></a>
      </li>


      <!-- Loop through all Topics on Sidebar-->
      {% for topic in topics %}
      <li>
        <a href="{% url 'home' %}?q={{topic.name}}">{{ topic.name }}</a><span>{{ topic.room_set.all.count }}</span></a>
      </li>
      {% endfor %}
    </ul>

<!--More Button with Dropdown menu-->
    <a class="btn btn--link" href="{% url 'topics' %}">
      More
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>chevron-down</title>
        <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
      </svg>
    </a>
  </div>

base/templates/base/update_user.html
{% extends 'main.html' %}

{% block content %}
<!--Update User Container-->
    <main class="update-account layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'home' %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Edit your profile</h3>
                    </div>
                </div>

                <!--Form-->
                <div class="layout__body">
                    <form class="form" action="" method="POST" enctype="multipart/form-data">
                      {% csrf_token %}

                      <!--Form Field-->
                      {% for field in form %}
                        <div class="form__group">
                            <label for="profile_pic">{{ field.label }}</label>
                            {{ field }}
                        </div>
                        {% endfor %}

                        <!--Form Cancel/Update Buttons-->
                        <div class="form__action">
                            <a class="btn btn--dark" href="{% url 'home' %}">Cancel</a>
                            <button class="btn btn--main" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
      </div>
    </main>
    {% endblock content %}